### ISSUE TITLE
Howto uninstall / reinstall ?

### ISSUE THREAD

**Issue by rjcoelho** [erszcz/docsh#16]
Is deleting the ~/.erlang file is enough ? If I do that then install again I get 

===> Verifying dependencies...
===> Compiling docsh
src/docsh_embeddable.erl:10: Warning: type fname() is unused
src/docsh_embeddable.erl:19: Warning: missing specification for function lookup/2
src/docsh_embeddable.erl:26: Warning: variable 'M' is unused
src/docsh_embeddable.erl:27: Warning: variable 'F' is unused
src/docsh_embeddable.erl:27: Warning: variable 'M' is unused
src/docsh_embeddable.erl:27: Warning: this clause cannot match because a previous clause at line 26 always matches
src/docsh_embeddable.erl:38: Warning: missing specification for function key_to_module/1
src/docsh_embeddable.erl:61: Warning: variable 'Mod' is unused
src/docsh_embeddable.erl:82: Warning: variable 'Arities' is unused

src/docsh_shell.erl:21: Warning: missing specification for function h/3
src/docsh_shell.erl:25: Warning: missing specification for function s/1
src/docsh_shell.erl:29: Warning: missing specification for function s/3
src/docsh_shell.erl:33: Warning: missing specification for function t/1
src/docsh_shell.erl:36: Warning: missing specification for function t/3

src/docsh_beam.erl:46: Warning: missing specification for function name/1
src/docsh_beam.erl:48: Warning: missing specification for function abst/1
src/docsh_beam.erl:51: Warning: missing specification for function beam_file/1
src/docsh_beam.erl:53: Warning: missing specification for function source_file/1
src/docsh_beam.erl:55: Warning: missing specification for function source_file/2
src/docsh_beam.erl:57: Warning: missing specification for function attribute/2

**Comment by erszcz** [comment]
There's an `uninstall.sh` script on master branch for a while now:

```
$ cat uninstall.sh
#!/usr/bin/env bash

rm ~/.erlang ~/.erlang.d/user_default.{erl,beam}
```

It will leave the possibly empty `~/.erlang.d` directory behind. The three files it removes are everything docsh installs in your environment.

**Comment by erszcz** [comment]
In general, though, `install.sh` will not overwrite any of these files if they exist - in the case you have your own goodies there - but warn you and quit. The way docsh uses `~/.erlang` and `user_default.erl` is described in [manual setup](https://github.com/erszcz/docsh/blob/master/doc/manual-setup.md).

**Comment by erszcz** [comment]
@rjcoelho I'm closing the issue. Please let me know if you have any further questions.
