### ISSUE TITLE
No EDoc for modules distributed with Erlang/OTP

### ISSUE THREAD

**Issue by erszcz** [erszcz/docsh#7]
### Finding the source files

The assumption I had for generating documentation for OTP modules was that if Erlang was installed from source or via kerl, I could rely on `M:module_info/0` returning valid paths to source files in the local file system.
This assumption is invalid, as the `otp_src_VERSION.tar.gz` bundles come with precompiled `.beam` files - not just for the `bootstrap/` subtree, but also for the modules under `lib/`.
This means that the source file paths contained in the modules are valid on the build host, but are not valid on my or your machine, even though the source files are present in the distributed tarball. EDoc comments are extracted directly from the source, since they're not available in the AST / module debug info.

### Fixing the source paths

For the time being, it's possible to manually delete all the `.beam` files in the Erlang/OTP build directory and rebuild the whole tree. This allows for accessing standard Erlang/OTP EDoc comments without modification of docsh.

In the future, docsh should take this into consideration and try to heuristically rewrite the known build-host-valid paths to local paths so that no end-user intervention is necessary.

**Comment by erszcz** [comment]
Done in #10 as long the sources are installed along with the .beam files.

The approach taken works with [asdf](https://github.com/asdf-vm/asdf) and [kerl](https://github.com/kerl/kerl). It's almost sure that it does with Erlang installed straight from a tarball. Not tested with Homebrew or ESL packages yet.

**Comment by kzemek** [comment]
Just tested on homebrew installation, everything seems to work properly 🎉

**Comment by erszcz** [comment]
Should work with ESL macOS packages based on their contents, too. Checked against https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_19.3~osx~10.10_amd64.dmg with lsbom as described in https://apple.stackexchange.com/a/125233.

**The known caveat is that the approach taken will not work on Linux distros which do not bundle source code by default (_wink, wink_, Debian).** I'm not convinced this is a significant problem, since developers will most probably install Erlang in one of the former methods anyway to be able to switch between versions easily. To be addressed if it turns out to be a significant problem.
